# -*- coding: utf-8 -*-
"""Proyek Analisis Data dengan Streamlit

Automatically generated by Colab.

# Proyek Analisis Data: [E-commerce-public-dataset]
- **Nama:** [Indra Mauludani Efendi]
- **Email:** [IndraMauludani09@gmail.com]
- **ID Dicoding:** [indramauludani14]
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import streamlit as st

# Title and Description
st.title('Proyek Analisis Data E-Commerce')
st.write("""
## Pertanyaan Bisnis:
1. Apakah terdapat hubungan antara harga produk (price) dan biaya pengiriman (freight_value)?
2. Bagaimana distribusi metode pembayaran yang digunakan oleh pelanggan, dan apakah metode pembayaran tertentu cenderung digunakan untuk transaksi dengan nilai yang lebih tinggi?
""")

# Display cleaned datasets
st.write("### Data Order Items")
st.dataframe(order_items_clean)

st.write("### Data Order Payments")
st.dataframe(order_payments_clean)

# Data assessment section
st.write("### Informasi Dataset Order Items:")
st.text(order_items_clean.info())

st.write("### Informasi Dataset Order Payments:")
st.text(order_payments_clean.info())

# Exploratory Data Analysis
st.write("### Eksplorasi Data")
st.write("#### Statistik Deskriptif - Order Items")
st.dataframe(order_items_clean.describe())

st.write("#### Statistik Deskriptif - Order Payments")
st.dataframe(order_payments_clean.describe())

# Analysis: Relationship between price and freight_value
st.write("### Analisis Hubungan Harga Produk dan Biaya Pengiriman")
correlation = order_items_clean[['price', 'freight_value']].corr()
st.write("Korelasi antara harga produk dan biaya pengiriman:")
st.dataframe(correlation)

# Scatter plot for price vs freight_value
st.write("#### Scatter Plot: Hubungan antara Harga dan Biaya Pengiriman")
fig, ax = plt.subplots(figsize=(10, 6))
sns.scatterplot(x='price', y='freight_value', data=order_items_clean, color='#2ecc71', ax=ax)
plt.title("Hubungan antara Harga Produk dan Biaya Pengiriman")
plt.xlabel("Harga Produk")
plt.ylabel("Biaya Pengiriman")
st.pyplot(fig)

# Analysis of payment methods
st.write("### Analisis Distribusi Metode Pembayaran")
payment_method_freq = order_payments_clean['payment_type'].value_counts()
st.write("Frekuensi Metode Pembayaran:")
st.dataframe(payment_method_freq)

# Bar plot for payment method distribution
st.write("#### Bar Plot: Distribusi Metode Pembayaran")
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x=payment_method_freq.index, y=payment_method_freq.values, color='#2ecc71', ax=ax)
plt.title("Distribusi Metode Pembayaran")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Frekuensi")
st.pyplot(fig)

# Box plot for payment values by payment method
st.write("#### Box Plot: Distribusi Nilai Pembayaran per Metode Pembayaran")
fig, ax = plt.subplots(figsize=(10, 6))
sns.boxplot(x='payment_type', y='payment_value', data=order_payments_clean, showfliers=False, color='#2ecc71', ax=ax)
sns.stripplot(x='payment_type', y='payment_value', data=order_payments_clean, jitter=True, color='#2ecc71', alpha=0.6, ax=ax)
plt.title("Distribusi Nilai Pembayaran per Metode Pembayaran")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Nilai Pembayaran")
st.pyplot(fig)

# Conclusion
st.write("### Kesimpulan")
st.write("""
- Korelasi antara harga produk dan biaya pengiriman dapat memberikan wawasan tentang seberapa erat hubungan antara kedua variabel ini.
- Analisis distribusi metode pembayaran menunjukkan metode yang paling banyak digunakan oleh pelanggan.
""")
