# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [E-commerce-public-dataset]
- **Nama:** [Indra Mauludani Efendi]
- **Email:** [IndraMauludani09@gmail.com]
- **ID Dicoding:** [indramauludani14]

## Menentukan Pertanyaan Bisnis

- Apakah terdapat hubungan antara harga produk (price) dan biaya pengiriman (freight_value)?
- Bagaimana distribusi metode pembayaran yang digunakan oleh pelanggan, dan apakah metode pembayaran tertentu cenderung digunakan untuk transaksi dengan nilai yang lebih tinggi?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import streamlit as st

"""## Data Wrangling

### Gathering Data
"""

# Menampilkan seluruh dataset yang sudah dirapikan di output

# Menampilkan dataset Order Items yang sudah dirapikan
order_items_clean_all = order_items_clean

# Menampilkan dataset Order Payments yang sudah dirapikan
order_payments_clean_all = order_payments_clean

# Menampilkan dataset langsung di output
order_items_clean_all, order_payments_clean_all

"""**Insight:**
- Dari dataset Order Items yang sudah dirapikan, kita dapat mengamati bahwa harga produk (price) memiliki rentang yang bervariasi, dan biaya pengiriman (freight_value) sering kali tidak sebanding dengan harga produk. Produk dengan harga tinggi mungkin memiliki biaya pengiriman yang mirip dengan produk yang lebih murah, yang menunjukkan bahwa biaya pengiriman tidak sepenuhnya bergantung pada harga produk. Insight ini dapat menjadi dasar untuk mengevaluasi kebijakan pengiriman yang lebih dinamis, di mana produk dengan harga tinggi mungkin memerlukan penanganan pengiriman yang lebih hati-hati dan mahal. Sebaliknya, untuk produk yang lebih murah, perusahaan dapat menawarkan opsi pengiriman yang lebih hemat.


- Dalam dataset Order Payments, setelah pembersihan, terlihat bahwa metode pembayaran yang paling sering digunakan adalah kartu kredit, diikuti oleh metode seperti "boleto" dan transfer bank. Dari distribusi nilai transaksi yang dihubungkan dengan metode pembayaran, terlihat bahwa transaksi dengan nilai tinggi cenderung dilakukan melalui metode pembayaran tertentu, seperti kartu kredit. Hal ini mengindikasikan bahwa pelanggan cenderung lebih nyaman melakukan pembelian dengan nilai besar menggunakan metode pembayaran yang lebih fleksibel atau memberikan opsi cicilan. Informasi ini bisa digunakan untuk merancang promosi yang lebih tepat sasaran dengan menargetkan pelanggan yang sering melakukan transaksi bernilai tinggi melalui metode pembayaran tersebut.

### Assessing Data
"""

# Memeriksa informasi umum dari dataset order_items_clean
print("Informasi Dataset Order Items:")
print(order_items_clean.info())
print("\n")

# Memeriksa informasi umum dari dataset order_payments_clean
print("Informasi Dataset Order Payments:")
print(order_payments_clean.info())
print("\n")

# Memeriksa apakah ada data yang hilang (null values) di dataset order_items_clean
print("Cek data yang hilang di Dataset Order Items:")
print(order_items_clean.isnull().sum())
print("\n")

# Memeriksa apakah ada data yang hilang (null values) di dataset order_payments_clean
print("Cek data yang hilang di Dataset Order Payments:")
print(order_payments_clean.isnull().sum())
print("\n")

# Memeriksa apakah ada data duplikat di dataset order_items_clean
print("Cek data duplikat di Dataset Order Items:")
print(order_items_clean.duplicated().sum())
print("\n")

# Memeriksa apakah ada data duplikat di dataset order_payments_clean
print("Cek data duplikat di Dataset Order Payments:")
print(order_payments_clean.duplicated().sum())

"""**Insight:**
- tidak ada data yang hilang
- tidak ada juga duplikat data

### Cleaning Data
"""

# Menghapus baris yang memiliki data yang hilang (jika ada) di dataset order_items_clean
order_items_clean.dropna(inplace=True)

# Menghapus baris yang memiliki data yang hilang (jika ada) di dataset order_payments_clean
order_payments_clean.dropna(inplace=True)

# Menghapus data duplikat di dataset order_items_clean
order_items_clean.drop_duplicates(inplace=True)

# Menghapus data duplikat di dataset order_payments_clean
order_payments_clean.drop_duplicates(inplace=True)

# Mengubah kolom 'shipping_limit_date' di order_items_clean menjadi format datetime
order_items_clean['shipping_limit_date'] = pd.to_datetime(order_items_clean['shipping_limit_date'])

# Menghapus baris dengan harga (price) yang tidak valid (misal, harga negatif) di order_items_clean
order_items_clean = order_items_clean[order_items_clean['price'] >= 0]

# Menghapus baris dengan nilai pembayaran (payment_value) yang tidak valid (misal, nilai negatif) di order_payments_clean
order_payments_clean = order_payments_clean[order_payments_clean['payment_value'] >= 0]

# Menampilkan informasi dataset setelah dibersihkan
print("Dataset Order Items setelah dibersihkan:")
print(order_items_clean.info())
print("\n")

print("Dataset Order Payments setelah dibersihkan:")
print(order_payments_clean.info())

"""**Insight:**
- Setelah pembersihan, berapa banyak baris yang dihapus karena data yang hilang atau duplikat.
- Apakah ada anomali seperti harga atau pembayaran dengan nilai negatif yang telah diperbaiki.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Statistik Deskriptif untuk dataset Order Items
print("Statistik Deskriptif - Order Items:")
print(order_items_clean.describe())
print("\n")

# 2. Statistik Deskriptif untuk dataset Order Payments
print("Statistik Deskriptif - Order Payments:")
print(order_payments_clean.describe())
print("\n")

"""**Insight:**
- Order Items:
Distribusi Harga (price):

Rata-rata harga dan median akan memberikan informasi mengenai tingkat harga umum dari produk yang dijual.
Standar deviasi akan menunjukkan seberapa luas variasi harga produk.
Perhatikan nilai minimal dan maksimal untuk mengidentifikasi range harga dan potensi outlier.
Distribusi Biaya Pengiriman (freight_value):

Jika median biaya pengiriman signifikan lebih rendah dari rata-rata, ini menunjukkan adanya skewness atau beberapa outlier dengan biaya pengiriman yang sangat tinggi.
Variabilitas biaya pengiriman, seperti ditunjukkan oleh standar deviasi, akan mengindikasikan seberapa konsisten biaya pengiriman di antara berbagai pesanan.
- Frekuensi Metode Pembayaran:

Jika dataset termasuk jenis metode pembayaran, melihat distribusi metode pembayaran yang paling sering digunakan dapat membantu dalam memahami preferensi pembayaran pelanggan.
Nilai Pembayaran (payment_value):

Analisis median dan rata-rata dari nilai pembayaran akan memberikan wawasan tentang seberapa besar pengeluaran rata-rata pelanggan.
Perhatikan skewness dalam data pembayaran yang mungkin terindikasi dari perbedaan antara rata-rata dan median serta nilai maksimum yang sangat tinggi dibanding median.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Menghitung korelasi antara harga (price) dan biaya pengiriman (freight_value)
correlation = order_items_clean[['price', 'freight_value']].corr()
print("Korelasi antara harga dan biaya pengiriman:")
print(correlation)

# Scatter plot untuk hubungan antara harga dan biaya pengiriman
plt.figure(figsize=(10, 6))
sns.scatterplot(x='price', y='freight_value', data=order_items_clean, color='#2ecc71')  # Using the green color
plt.title("Hubungan antara Harga Produk dan Biaya Pengiriman")
plt.xlabel("Harga Produk")
plt.ylabel("Biaya Pengiriman")
plt.show()

# Insight
print("Insight: Korelasi yang dihasilkan dan scatter plot akan membantu dalam menganalisis hubungan.")

"""### Pertanyaan 2:"""

import matplotlib.pyplot as plt
import seaborn as sns

# Frekuensi penggunaan metode pembayaran
payment_method_freq = order_payments_clean['payment_type'].value_counts()
print("Frekuensi metode pembayaran:")
print(payment_method_freq)

# Bar plot untuk distribusi metode pembayaran
plt.figure(figsize=(10, 6))
sns.barplot(x=payment_method_freq.index, y=payment_method_freq.values, color='#2ecc71')  # Using a shade of green
plt.title("Distribusi Metode Pembayaran")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Frekuensi")
plt.show()

# Box plot dengan strip plot untuk distribusi nilai pembayaran per metode pembayaran
plt.figure(figsize=(10, 6))

# Box plot (using the same shade of green)
sns.boxplot(x='payment_type', y='payment_value', data=order_payments_clean, showfliers=False, color='#2ecc71')

# Strip plot (using the same shade of green for consistency)
sns.stripplot(x='payment_type', y='payment_value', data=order_payments_clean, jitter=True, color='#2ecc71', alpha=0.6)

plt.title("Distribusi Nilai Pembayaran per Metode Pembayaran dengan Distribusi Pembayaran")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Nilai Pembayaran")
plt.show()

# Insight
print("Insight: Analisis ini akan memberikan informasi tentang preferensi metode pembayaran serta transaksi bernilai tinggi.")

"""**Insight:**
- Korelasi antara harga produk dan biaya pengiriman dapat memberikan wawasan tentang seberapa erat hubungan antara kedua variabel ini. Jika nilai korelasi positif dan signifikan, ini menunjukkan bahwa harga produk yang lebih tinggi cenderung memiliki biaya pengiriman yang lebih tinggi pula. Hal ini bisa menjadi indikator bahwa biaya pengiriman dipengaruhi oleh nilai harga produk, mungkin karena faktor asuransi, penanganan khusus, atau ukuran paket yang lebih besar.
- Analisis distribusi metode pembayaran menunjukkan metode yang paling banyak digunakan oleh pelanggan. Misalnya, jika kartu kredit adalah metode yang paling sering digunakan, ini menandakan kepercayaan tinggi terhadap transaksi kredit dan mungkin kesediaan pelanggan untuk melakukan pembelian lebih besar via kredit.

## Conclusion

- Berdasarkan hasil korelasi dan visualisasi, dapat disimpulkan apakah ada hubungan antara harga produk dan biaya pengiriman. Jika terdapat korelasi yang kuat, hal ini dapat digunakan untuk mengoptimalkan kebijakan pengiriman.
- Dari analisis distribusi metode pembayaran, Anda dapat menyimpulkan metode pembayaran yang paling populer dan memahami preferensi pelanggan dalam memilih metode pembayaran untuk transaksi dengan nilai tertentu.
"""
